# Generated by Django 4.2.11 on 2024-05-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_is_employee_account_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agenda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='agenda_readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='stock_readonly',
            field=models.BooleanField(default=False),
        ),
    ]
