# Generated by Django 5.0.7 on 2024-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_agenda_account_agenda_readonly_account_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='studio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='studio_readonly',
            field=models.BooleanField(default=False),
        ),
    ]
