# Generated by Django 5.0.7 on 2024-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_account_studio_account_studio_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agenda_delete_machine_persons',
            field=models.BooleanField(default=False),
        ),
    ]
